"""
strength_analyzer.py
=====================
Password strength and entropy analysis for VaultForge.

This module never receives or stores generated passwords in any file or
database; it simply computes a strength category, an approximate entropy
figure, and some human-readable security tips from a password string that
already lives, briefly, in application memory.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from config import (
    DIGITS,
    ENTROPY_MEDIUM_MAX,
    ENTROPY_STRONG_MAX,
    ENTROPY_WEAK_MAX,
    LOWERCASE,
    SYMBOLS,
    UPPERCASE,
)

STRENGTH_WEAK = "Weak"
STRENGTH_MEDIUM = "Medium"
STRENGTH_STRONG = "Strong"
STRENGTH_VERY_STRONG = "Very Strong"


@dataclass(frozen=True)
class StrengthReport:
    """A snapshot analysis of one password's estimated strength."""

    length: int
    category_count: int
    pool_size: int
    entropy_bits: float
    strength: str
    tips: list[str] = field(default_factory=list)


def _detect_pool_size(password: str) -> tuple[int, int]:
    """Estimate the character pool size actually used by ``password``.

    Returns a tuple of (pool_size, category_count) based on which of the
    four standard categories appear anywhere in the password. This is an
    approximation — it assumes the password draws from the full standard
    alphabets, which is true for anything generated by this application.
    """
    pool_size = 0
    category_count = 0

    if any(c in UPPERCASE for c in password):
        pool_size += len(UPPERCASE)
        category_count += 1
    if any(c in LOWERCASE for c in password):
        pool_size += len(LOWERCASE)
        category_count += 1
    if any(c in DIGITS for c in password):
        pool_size += len(DIGITS)
        category_count += 1
    if any(c in SYMBOLS for c in password):
        pool_size += len(SYMBOLS)
        category_count += 1

    # Anything outside the four known pools (unlikely for generated
    # passwords, but possible if a user pastes in something custom) is
    # counted conservatively as one extra "unknown" character each.
    known_chars = set(UPPERCASE + LOWERCASE + DIGITS + SYMBOLS)
    unknown_chars = {c for c in password if c not in known_chars}
    if unknown_chars:
        pool_size += len(unknown_chars)
        category_count += 1

    return pool_size, category_count


def calculate_entropy_bits(password: str) -> float:
    """Approximate Shannon entropy of the password in bits.

    Formula: entropy = length * log2(pool_size)

    This is a standard, widely used approximation for random passwords
    drawn uniformly from a known character pool. It is not a guarantee of
    resistance against any specific attack.
    """
    if not password:
        return 0.0

    pool_size, _ = _detect_pool_size(password)
    if pool_size <= 1:
        return 0.0

    return len(password) * math.log2(pool_size)


def classify_strength(entropy_bits: float) -> str:
    """Map an entropy value (bits) to a human-readable strength category."""
    if entropy_bits < ENTROPY_WEAK_MAX:
        return STRENGTH_WEAK
    if entropy_bits < ENTROPY_MEDIUM_MAX:
        return STRENGTH_MEDIUM
    if entropy_bits < ENTROPY_STRONG_MAX:
        return STRENGTH_STRONG
    return STRENGTH_VERY_STRONG


def _generate_tips(password: str, category_count: int, strength: str) -> list[str]:
    """Produce a short list of actionable, honest security tips."""
    tips: list[str] = []

    if len(password) < 12:
        tips.append("Consider a length of 12+ characters for stronger protection.")
    if category_count < 3:
        tips.append("Add more character types (upper, lower, digits, symbols) to increase diversity.")
    if strength in (STRENGTH_WEAK, STRENGTH_MEDIUM):
        tips.append("Use a unique password for every account and a password manager to store it.")
    if not tips:
        tips.append("This password has strong length and character diversity for its category mix.")

    tips.append("No password strength estimate can guarantee resistance to every possible attack.")
    return tips


def analyze_password(password: str) -> StrengthReport:
    """Produce a full strength report for a password.

    Args:
        password: The password string to analyze (held only in memory).

    Returns:
        A ``StrengthReport`` describing length, diversity, entropy, an
        overall strength category, and a short list of tips.
    """
    pool_size, category_count = _detect_pool_size(password)
    entropy_bits = calculate_entropy_bits(password)
    strength = classify_strength(entropy_bits) if password else STRENGTH_WEAK
    tips = _generate_tips(password, category_count, strength) if password else []

    return StrengthReport(
        length=len(password),
        category_count=category_count,
        pool_size=pool_size,
        entropy_bits=entropy_bits,
        strength=strength,
        tips=tips,
    )


def strength_to_fraction(strength: str) -> float:
    """Convert a strength label into a 0.0-1.0 fraction for a progress bar."""
    mapping = {
        STRENGTH_WEAK: 0.25,
        STRENGTH_MEDIUM: 0.55,
        STRENGTH_STRONG: 0.8,
        STRENGTH_VERY_STRONG: 1.0,
    }
    return mapping.get(strength, 0.0)
